global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
- job_name: minio-job
  bearer_token: token
  metrics_path: /minio/v2/metrics/cluster
  scheme: http
  static_configs:
  - targets: ['minio-url']
